---
- hosts: all
  gather_facts: true
  roles:
    - role: geerlingguy.docker
      become: true

  tasks:
    - name: Check if already listening to tcp 
      shell: 
        cmd: grep -nrw -e '-H tcp://0.0.0.0:2375' /etc/systemd/system/docker.service
      ignore_errors: true
      register: check_tcp_listener

    - name: Set listening on tcp
      become: true    
      ansible.builtin.replace:
        path: /lib/systemd/system/docker.service
        regexp: '(-H fd:\/\/)'
        replace: '-H fd:// -H tcp://0.0.0.0:2375'
      when: check_tcp_listener.stdout == ''

    - name: Reload and restart docker daemon
      become: true    
      ansible.builtin.systemd: 
        name: docker
        daemon_reload: true
        state: restarted       

    - name: Add user 'vagrant' to group 'docker'
      become: true    
      ansible.builtin.user:
        name: 'vagrant'
        groups: docker
        append: yes 
